name: DevelopmentCI/CD
on:
  push:
    branches:
      - "develop"
env:
  IMAGE_NAME: smartgarbage-net
  AZURE_WEBAPP_NAME: smartgarbage-api-dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout 
        uses: actions/checkout@v4 

      - name: Setup .NET 
        uses: actions/setup-dotnet@v4
        with: 
          dotnet-version: 8.0.x
      
      - name: Restore dependencies
        run: dotnet restore vstudy.smartgarbage

      - name: Build
        run: dotnet build vstudy.smartgarbage --configuration Release --no-restore

      - name: Test
        run: dotnet test vstudy.smartgarbage --no-restore --verbosity normal

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6 
        with: 
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:develop

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PROFILE }}
          images: 'ghcr.io/${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:develop'