version: '3.8'

services:
  backend:
    image: my-dotnet-app:latest
    container_name: dotnet-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ORACLE_HOST=db
      - ORACLE_USER=oracleuser
      - ORACLE_PASSWORD=oraclepass
    depends_on:
      - db

  db:
    image: oracle/database:21.3.0
    container_name: oracle-db
    environment:
      ORACLE_PWD: oraclepass
    ports:
      - "1521:1521"
    volumes:
      - oradata:/opt/oracle/oradata